# Generated by Django 2.2.1 on 2020-03-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_geopoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='geopoint',
            name='description',
            field=models.CharField(default='No description', max_length=100),
        ),
    ]
