# Generated by Django 2.2.1 on 2020-03-24 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_geopoint_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='geopoint',
            name='country_name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='world.WorldBorder'),
        ),
    ]
